version: '3'

services:
  
  client:
    build: client
    ports:
      - 80:80

  server:
    build: server
    ports:
      - 5000:5000

  db:
    image: mongo:latest
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
