version: '3'

services:
  
  client:
    build: client
    ports:
      - 80:80

  server:
    build: server
    ports:
      - 5000:5000
    volumes:
      - ~/projects/react-flask-app/server:/app

  db:
    image: mongo:4.2.6
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    volumes:
      - ~/projects/react-flask-app/scripts:/scripts
      - ~/projects/react-flask-app/data/db:/data/db
